### PR TITLE
Update to 1.17.1 & Add the available settings

### PR DESCRIPTION
**Pull request by jensvh**

### CODE REVIEW

**Comment by jensvh** [comment]
@RunTheBot Thanks for letting me know!

**Comment by eatmyvenom** [comment]
Has this been tested?

**Comment by eatmyvenom** [comment]
As soon as someone can verify this working on a vanilla server I'll merge this and probably publish a build

**Comment by jensvh** [comment]
I've published a build on my fork for testing purposes. Feel free to test it yourself. I've used it for around a week now and everything seems to works fine on a survival Paper server. The only thing that i couldn't get to work is water placing.

**Comment by eatmyvenom** [comment]
Good enough for me

**Comment by pofdzm** [comment]
is there gonna be a release file for 1.17.1?

**Comment by jensvh** [comment]
On my fork their should be a release for 1.17.1 that you can use in the meantime.

**Comment by pofdzm** [comment]
> On my fork their should be a release for 1.17.1 that you can use in the meantime.

Your fork gave me an error about fabric version, i went one fabric version back and then it did not gave that error but there is still other errors. Should I open an issue?

**Comment by jensvh** [comment]
You could open an issue if you want. I just tested the release of my fork and everything seems to work fine. Could you share the exact error message and which fabric version you're on? Then i'll take a look.

**Comment by pofdzm** [comment]
> You could open an issue if you want. I just tested the release of my fork and everything seems to work fine. Could you share the exact error message and which fabric version you're on? Then i'll take a look.

there is actually not a button to open an issue on your repository for some reason, but here this is the output i get;
`[20:46:12] [main/INFO]: Loading for game Minecraft 1.17.1
[20:46:12] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: litematica_printer requires {fabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-loader-0.11.6.jar:?]
	... 13 more
Process exited with code 1.`

**Comment by pofdzm** [comment]
oh sorry, my dumbness, i realized i didnt installed the fabric api

**Comment by jensvh** [comment]
No worries, great to hear you've got it working.

**Pull request merged**
