### PR TITLE
Edited fabric.mod.json

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Changes:

1) I renamed the mod, because: as much as I like "litematica brrrrrrrrrrrrrifier", it was confusing other people who I shows my mod list to.
2) Added a description, mod-id, author and links because you couldn't be bothered to.
3) Made litematica_printer display as an extension to litematica in modmenu, as seen below:

image

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
Note that these changes went through multiple iterations (and fuck ups, which should hopefully be fixed), so it would be better to look at 'files changed' rather than each commit individually.

**Comment by eatmyvenom** [comment]
I just got a notification for this today right now.

**Comment by eatmyvenom** [comment]
Uh the Readme is your Readme for your repo. Would you mind removing that. Then I can probably merge.

**Comment by DragonEggBedrockBreaking** [comment]
yeah, sorry, forgot about this pr so i mindlessly changed the readme
changed it back now

**Comment by eatmyvenom** [comment]
Very epic thanks

**Pull request merged**
